services:
  app:
    container_name: api
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.docker
    depends_on:
      - db
      - minio
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
      - CONFIG_APP_PORT=3000
      - CONFIG_DB_HOST=db
      - CONFIG_DB_PORT=5432
      - CONFIG_DB_USER=postgres
      - CONFIG_DB_PASSWORD=admin
      - CONFIG_DB_NAME=postgres
      - CONFIG_DB_MAX_CONNECTIONS=20
      - CONFIG_REDIS_HOST=redis
      - CONFIG_REDIS_PORT=6379
      - CONFIG_REDIS_EC_CLUSTER=false
      - CONFIG_REDIS_DISABLE_TLS=true
      - CONFIG_REDIS_DISABLE_TLS_REJECT_UNAUTHORIZED=false
      - CONFIG_REDIS_RECONNECT_MAX_WAIT=3000
      - CONFIG_REDIS_LOCAL_SETUP=true
      - CONFIG_MINIO_ENDPOINT=minio
      - CONFIG_MINIO_PORT=9000
      - CONFIG_MINIO_ACCESS_KEY=root
      - CONFIG_MINIO_SECRET_KEY=minioadmin
      - CONFIG_JWT_SECRET=my-secret-key
    networks:
      - server_network

  db:
    image: pgvector/pgvector:pg16
    container_name: pgvector
    command: ["postgres", "-c", "log_statement=all"]
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    volumes:
      - ./.data/docker/postgresql:/var/lib/postgresql
    ports:
      - "5433:5432"
    networks:
      - server_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 30s
      retries: 5

  minio:
    image: quay.io/minio/minio
    container_name: minio
    command: ["minio", "server", "/data", "--console-address", ":9001"]
    volumes:
      - ./.data/docker/minio:/data
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: minioadmin
    networks:
      - server_network


  redis:
    image: redis/redis-stack:latest
    restart: always
    container_name: redis-stack
    ports:
      - 6379:6379
    volumes:
      - ./.data/docker/redis:/var/lib/redis
    networks:
      - server_network

  db-migrations:
    container_name: db-migrations
    build:
      context: .
      dockerfile: Dockerfile-migrations
    depends_on:
      - db
      - app
    environment:
      - CONFIG_DB_HOST=db
      - CONFIG_DB_PORT=5432
      - CONFIG_DB_USER=postgres
      - CONFIG_DB_PASSWORD=admin
      - CONFIG_DB_NAME=postgres
      - CONFIG_DB_MAX_CONNECTIONS=20
    command: ["bash", "-c", "bash /migration_entrypoint.sh; npm run migrate:up"]
    networks:
      - server_network

networks:
  server_network:
    driver: bridge
